baseURL = "https://waynegm.github.io/"
languageCode = "en-us"
title = "WM Seismic Solutions"
theme = "universal"
googleAnalytics = "G-8TDBM2EMZX"
publishDir = "docs"


[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="faq"
    name = "Services"
    url  = "/services/"
    weight = 2

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4


# Top bar social links menu

[[menu.social]]
    weight = 1
    name = "Github"
    url = "https://github.com/waynegm"
    pre = "<i class='fab fa-2x fa-github' style='padding: 20px 0;'></i>"
    
[[menu.social]]
    weight = 2
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/waynemogg/"
    pre = "<i class='fab fa-2x fa-linkedin' ></i>"
    
[params]
    author = "Wayne Mogg"
    style = "green"
    mainSections = ["blog"]
        # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    formspree_action = "https://formspree.io/f/xayaygyo"
    contact_form_ajax = false
    
    logo = "img/logo.png"
    logo_small = "img/logo_small.png"
    
    copyright = "Copyright (c) 2021, Wayne Mogg; all rights reserved."

[permalinks]
    blog = "/blog/:filename/"
    
[params.carousel]
    enable = true
    
[params.recent_posts]
    enable = true
    title = "Recent Articles"
    subtitle = ""
    banners = false

[params.widgets]
    search = true
    categories = true
    tags = true
    
[params.clients]
    enable = true
    title = "Clients"
    subtitle = ""
    
